version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"

    volumes:
      - .:/app

    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
      - DATABASE_URL=sqlite:///instance/database.db

    #volumes:
    #  - ./instance:/app/instance  # database.db sqlite
    # depends_on:
    #  - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
